services:
    # A background worker that consumes a queue
    - type: worker
      name: sylvabot node worker
      env: node
      buildCommand: npm i
      startCommand: npm run migrate && npm run start:prod
      plan: starter
      envVars:
          - key: DB_HOST
            fromService:
                type: postgres
                name: sylvabot
                property: host
          - key: DB_PASSWORD
            fromService:
                type: postgres
                name: sylvabot
                property: password
          - key: DB_NAME
            fromService:
                type: postgres
                name: sylvabot
                property: database
          - key: DB_USER
            fromService:
                type: postgres
                name: sylvabot
                property: user

databases:
    - name: sylvabot
      databaseName: sylvabot
      ipAllowList: []
      plan: free
