services:
    # A background worker that consumes a queue
    - type: worker
      name: sylvabot node worker
      env: node
      buildCommand: npm i
      startCommand: npm run start:prod
      plan: starter

databases:
    - name: sylvabot
      databaseName: sylvabot
      ipAllowList: []
      plan: free
