services:
    # A background worker that consumes a queue
    - type: worker
      name: bot
      env: node
      startCommand: npm run start
      plan: starter

databases:
    - name: sylvabot
      databaseName: sylvabot
      ipAllowList: []
      plan: free
